### ISSUE TITLE
Replace `\markdownRendererHorizontalRule` with `\markdownRendererThematicBreak`

### ISSUE THREAD

**Issue by Witiko** [drehak/pandoc-to-markdown#14]
In development version 2.17.1-34-g8a40d72 (to be released to CTAN as version 2.18.0 at the end of October), the Markdown package has renamed the `\markdownRendererHorizontalRule` to `\markdownRendererThematicBreak`. See also https://github.com/Witiko/markdown/issues/187 and https://github.com/Witiko/markdown/pull/201. The `\markdownRendererHorizontalRule` command will be removed in Markdown 3.0.0.

The pandoc-to-markdown bridge still uses the `\markdownRendererHorizontalRule` command:
https://github.com/drehak/pandoc-to-markdown/blob/9eb268b80c3dd60af15ccd7a141d610de857ffa4/pandoc-to-markdown.tex#L57

**Comment by drehak** [comment]
Looks good, will be merged after Markdown 2.18.0 is released.
