### ISSUE TITLE
Remove attribute support from `pandoc-to-markdown.lua`

### ISSUE THREAD

**Issue by Witiko** [drehak/pandoc-to-markdown#7]
The `Div` and `Span` functions in `pandoc-to-markdown.lua` produce TeX commands that take a list of attributes as their first parameter. The argument-parsing function has not yet been implemented:

https://github.com/drehak/pandoc-to-markdown/blob/e288e85d59b69c5df229fbb37b2c707481edddfa/pandoc-to-markdown.lua#L39-L42

This seems overly ambitious for our minimum viable product that we are trying to finish before the TUGboat article has been published. I have opened issue https://github.com/Witiko/markdown/issues/126 that fast-tracks the addition of support for div and span attributes as a part of [Markdown 2.16.0][1], but I would suggest that we revert the support for attributes from `pandoc-to-markdown` for now.

 [1]: https://github.com/Witiko/markdown/milestone/8

**Comment by drehak** [comment]
Removed the attributes, for now they're preserved on the `feature/attributes` branch.
