### ISSUE TITLE
Add missing functions to `pandoc-to-markdown.lua`

### ISSUE THREAD

**Issue by Witiko** [drehak/pandoc-to-markdown#8]
We should implement the following functions in `pandoc-to-markdown.lua`:

- [x] `BlockQuote`
- [x] `Cite`
- [x] `Image`
- [x] `LineBlock`
- [x] `Link`
- [x] ~~`Null`~~
- [x] `OrderedList`
- [x] `RawBlock`
- [x] `RawInline`
- [x] `Table`

**Comment by drehak** [comment]
`Null` is never invoked.

**Comment by Witiko** [comment]
> `Null` is never invoked.

@drehak How do we know? Have you looked at the Haskell code or just tried a couple documents?

**Comment by drehak** [comment]
@Witiko There seems to be no custom writer method that's invoked, just an empty string.

https://github.com/jgm/pandoc/blob/c0584bc69925bcd39186391f6e83e4af90605c07/src/Text/Pandoc/Writers/Custom.hs#L138
